kind = "web"
previewPath = "/"
title = "Black Galaxy"
version = "1.0.0"
id = "artifacts/black-galaxy"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19258

[services.development]
run = "pnpm --filter @workspace/black-galaxy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/black-galaxy", "run", "build" ]
publicDir = "artifacts/black-galaxy/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19258"
BASE_PATH = "/"
